[workspace]
resolver = "2"
members = [
    "crates/ds4-sys",
    "crates/ds4-core",
    "crates/ds4-cli",
    "crates/ds4-kv",
    "crates/ds4-web",
    "crates/ds4-server",
    "crates/ds4-dist",
    "crates/ds4-perf",
    "crates/ds4-perf-gpu",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
publish = false
