#!/usr/bin/env python3
"""CPU PyTorch vectors for the published Inkling MoE precision contract."""
import argparse
import hashlib
import json
from pathlib import Path

import torch
from torch.nn import functional as F


ROUTED, USED, SHARED = 256, 6, 2
CASES, WIDTH, ACT_WIDTH = 8, 17, 97


def emit(name, tensor, integer=False):
    flat = tensor.flatten().tolist()
    values = [str(x) if integer else float(x).hex() + "f" for x in flat]
    lines = [", ".join(values[i:i + 6]) for i in range(0, len(values), 6)]
    typ = "int32_t" if integer else "float"
    return f"static const {typ} {name}[{len(flat)}] = {{\n    " + ",\n    ".join(lines) + "\n};\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    torch.set_num_threads(1)
    logits = torch.empty(CASES, ROUTED + SHARED)
    bias = torch.zeros(CASES, ROUTED)
    scale = torch.tensor([0.375, 1.0, 1.7, 0.9, 1.0, 1.0, 0.0, 1.0])
    expert = torch.arange(ROUTED + SHARED)
    logits[0] = ((expert * 37 + 11) % 251 - 125) / 19.0
    bias[0] = ((torch.arange(ROUTED) * 13) % 41 - 20) / 37.0
    logits[1].zero_()  # Stable lower-ID tie break.
    logits[2] = -3.0
    bias[2, 121:127] = torch.arange(USED) / 16.0 + 2.0
    logits[2, 121:127] = torch.arange(USED) / 8.0 - 7.0
    logits[2, ROUTED:] = torch.tensor([2.0, -1.0])
    logits[3] = -4.0
    logits[3, ROUTED:] = 1000.0  # Shared logits participate in the same norm.
    logits[4] = -1000.0
    logits[4, :USED] += torch.arange(USED)
    logits[4, ROUTED:] = torch.tensor([-998.0, -1007.0])
    logits[5] = 1000.0
    logits[5, ROUTED:] = -1000.0
    logits[6] = logits[0]
    logits[7] = (expert - ROUTED) / 32.0  # Replay must change IDs and weights.
    scores = logits[:, :ROUTED].sigmoid() + bias
    ids = torch.argsort(scores, descending=True, stable=True)[:, :USED]
    selected = torch.cat([logits.gather(1, ids), logits[:, ROUTED:]], dim=1)
    lp = F.logsigmoid(selected)
    weights = (lp - torch.logsumexp(lp, dim=1, keepdim=True)).exp()
    weights = weights * (USED + SHARED) * scale[:, None]

    row = torch.arange(CASES)[:, None]
    col = torch.arange(ACT_WIDTH * 2)[None, :]
    gateup = (((row * 29 + col * 17) % 251) - 125) / 13.0
    gateup[:, :8:2] = torch.tensor([-1000.0, 1000.0, 0.0, -0.0])
    gammas = torch.tensor([0.0, 1.0, 0.125, 3.7, 0.25, 1.2345, 8.0, 0.9])
    bf = gateup.to(torch.bfloat16).float()
    activation = F.silu(bf[:, ::2]) * bf[:, 1::2]
    act_plain = activation.to(torch.bfloat16).float()
    act_weighted = (activation * gammas[:, None]).to(torch.bfloat16).float()

    r = torch.arange(CASES * USED * WIDTH).reshape(CASES, USED, WIDTH)
    routed = (((r * 19) % 257) - 128).float() / 31.0
    s = torch.arange(CASES * SHARED * WIDTH).reshape(CASES, SHARED, WIDTH)
    shared = (((s * 23) % 139) - 69).float() / 17.0
    # BF16 expert output first; routed gamma is applied AFTER the down GEMM.
    rsum = (routed.to(torch.bfloat16).float() * weights[:, :USED, None]).sum(1)
    ssum = shared.to(torch.bfloat16).float().sum(1)
    combined = (rsum.to(torch.bfloat16) + ssum.to(torch.bfloat16)).float()
    out = "/* Generated by make_moe_vectors.py; no model weights. */\n"
    out += f"/* PyTorch {torch.__version__}, CPU FP32/BF16. */\n"
    out += f"enum {{ REF_CASES = {CASES}, REF_WIDTH = {WIDTH}, REF_ACT_WIDTH = {ACT_WIDTH} }};\n"
    for name, tensor in [
        ("ref_logits", logits), ("ref_bias", bias), ("ref_scale", scale),
        ("ref_weights", weights), ("ref_gateup", gateup), ("ref_gammas", gammas),
        ("ref_act_plain", act_plain), ("ref_act_weighted", act_weighted),
        ("ref_routed", routed), ("ref_shared", shared), ("ref_combined", combined),
    ]:
        out += emit(name, tensor)
    out += emit("ref_ids", ids, integer=True)
    args.output.write_text(out)
    args.output.with_suffix(".json").write_text(json.dumps({
        "torch": torch.__version__, "device": "cpu",
        "source_revision": "8cc5877b44d343f88b92086aa1fb72897950f06a",
        "sglang_revision": "03d06a764e4a83268eefd1bafc676418f7269c89",
        "fixture_sha256": hashlib.sha256(out.encode()).hexdigest(),
        "scope": "Published MoE equations, stable lower-ID selection, BF16 boundaries; not full SGLang runtime parity",
    }, indent=2) + "\n")


if __name__ == "__main__":
    main()
